langfuse:
  # -- Core Langfuse application configuration
  langfuse:
    # TODO: Auth through Google OAuth
    # -- Security
    salt:
      value: "mysalt"
    nextauth:
      secret:
        value: "mysecret"
    encryptionKey:
      value: "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo"

    # -- Telemetry
    features:
      telemetryEnabled: false
      experimentalFeaturesEnabled: true

    # -- Init org/project/user for bootstrapping - Not needed if we manage auth through Google...?
    additionalEnv:
      - name: LANGFUSE_INIT_ORG_ID
        value: "patchdb"
      - name: LANGFUSE_INIT_ORG_NAME
        value: "patchdb"
      - name: LANGFUSE_INIT_PROJECT_ID
        value: "patchdb"
      - name: LANGFUSE_INIT_PROJECT_NAME
        value: "patchdb"
      - name: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
        value: "publickey"
      - name: LANGFUSE_INIT_PROJECT_SECRET_KEY
        value: "secretkey"
      - name: LANGFUSE_INIT_USER_EMAIL
        value: "eng-testing@patchdb.app"
      - name: LANGFUSE_INIT_USER_NAME
        value: "testing-user"
      - name: LANGFUSE_INIT_USER_PASSWORD
        value: "password"

    # -- Web service
    web:
      replicas: 1

    # -- Worker service
    worker:
      replicas: 1

  # -- PostgreSQL sub-chart configuration
  postgresql:
    # TODO: Host elsewhere
    # deploy: false
    # host: <host-url.com>
    auth:
      username: postgres
      password: postgres
      database: postgres

  # -- ClickHouse sub-chart configuration
  clickhouse:
    auth:
      # TODO: Secrets
      username: clickhouse
      password: clickhouse
    replicaCount: 1
    resourcesPreset: small

  # -- Redis sub-chart configuration
  redis:
    # TODO: Host elsewhere
    # deploy: false
    # host: <host-url.com>
    auth:
      password: myredissecret

  # -- S3 (MinIO) sub-chart configuration
  s3:
    # TODO: Host elsewhere (Azure Blob Storage)
    auth:
      rootUser: minio
      rootPassword: miniosecret
    defaultBuckets: langfuse
