harbor:
  externalURL: https://harbor.patchdb.se

  expose:
    type: clusterIP
    tls:
      enabled: false

  # POC mode: no persistent volumes available. Harbor data will be lost on restart.
  persistence:
    enabled: false

  # Reduce footprint for a small cluster / POC.
  trivy:
    enabled: false
  notary:
    enabled: false
  chartmuseum:
    enabled: false


