apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: alexk8s-test-proj
      auth:
        workloadIdentity:
          clusterName: {{ .Values.clusterName }}
          clusterLocation: {{ .Values.clusterLocation }}
          serviceAccountRef:
            name: {{ (index .Values "external-secrets" "serviceAccount" "name") }}
            namespace: {{ .Release.Namespace }}
