clusterName: alexk8s-test-proj-cluster
clusterLocation: europe-north2

external-secrets:
  serviceAccount:
    create: true
    name: external-secrets-sa
    annotations:
      iam.gke.io/gcp-service-account: external-secrets-sa@alexk8s-test-proj.iam.gserviceaccount.com