apiVersion: v2
name: prometheus
type: application
version: 1.0.0
description: Helm chart for Prometheus
dependencies:
  - name: prometheus
    version: 28.8.0
    repository: https://prometheus-community.github.io/helm-charts