apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mssql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AlexHag/k8.git
    targetRevision: HEAD
    path: apps/mssql/
  destination:
    server: https://kubernetes.default.svc
    namespace: mssql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true