apiVersion: v1
kind: Service
metadata:
  name: my-py-app-service
  namespace: default
  labels:
    app: my-py-app
spec:
  selector:
    app: my-py-app
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
