apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-google-oauth
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-google-oauth
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: argocd-oauth-client-id
    - secretKey: client-secret
      remoteRef:
        key: argocd-oauth-client-secret

